import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from '@react-pdf/renderer';
import { formatMoneyCents } from '@/lib/format/time';

// Fonts: @react-pdf ships Helvetica variants built-in so no font-loader setup
// is needed. If we later want a custom typeface we can Font.register() it.
const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: '#111111',
  },
  eyebrow: {
    fontSize: 9,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    color: '#6b6b6b',
    marginBottom: 6,
  },
  title: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 12,
    color: '#555',
    marginBottom: 24,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  stat: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 6,
    padding: 12,
  },
  statLabel: {
    fontSize: 8,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    color: '#6b6b6b',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
  },
  narrativeBox: {
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 6,
    padding: 16,
  },
  narrativeLabel: {
    fontSize: 8,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    color: '#6b6b6b',
    marginBottom: 8,
  },
  narrativeBody: {
    fontSize: 11,
    lineHeight: 1.5,
    color: '#222',
  },
  footer: {
    marginTop: 32,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
    fontSize: 9,
    color: '#888',
  },
});

export type ReportPdfData = {
  month: string;
  companyName: string;
  runsCount: number;
  timeSavedMinutes: number;
  dollarsInfluencedCents: number;
  narrativeMd: string | null;
};

function ReportDocument({ data }: { data: ReportPdfData }) {
  return (
    <Document title={`Raijuu report — ${data.month}`}>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.eyebrow}>Raijuu monthly report</Text>
        <Text style={styles.title}>{data.companyName}</Text>
        <Text style={styles.subtitle}>{data.month}</Text>

        <View style={styles.statsRow}>
          <View style={styles.stat}>
            <Text style={styles.statLabel}>Runs this month</Text>
            <Text style={styles.statValue}>{data.runsCount}</Text>
          </View>
          <View style={styles.stat}>
            <Text style={styles.statLabel}>Time saved</Text>
            <Text style={styles.statValue}>
              {data.timeSavedMinutes} min
            </Text>
          </View>
          <View style={styles.stat}>
            <Text style={styles.statLabel}>Dollars influenced</Text>
            <Text style={styles.statValue}>
              {formatMoneyCents(data.dollarsInfluencedCents)}
            </Text>
          </View>
        </View>

        {data.narrativeMd && data.narrativeMd.trim().length > 0 && (
          <View style={styles.narrativeBox}>
            <Text style={styles.narrativeLabel}>Notes from Raijuu</Text>
            <Text style={styles.narrativeBody}>{data.narrativeMd}</Text>
          </View>
        )}

        <Text style={styles.footer}>
          Generated by Raijuu AI Automation · raijuu.ai
        </Text>
      </Page>
    </Document>
  );
}

export async function renderReportPdf(data: ReportPdfData): Promise<Buffer> {
  return renderToBuffer(<ReportDocument data={data} />);
}
